export const countries = [
    { code: 'AR', name: 'Argentina', flag: '🇦🇷', callingCode: '+54' },
    { code: 'BO', name: 'Bolivia', flag: '🇧🇴', callingCode: '+591' },
    { code: 'CL', name: 'Chile', flag: '🇨🇱', callingCode: '+56' },
    { code: 'CO', name: 'Colombia', flag: '🇨🇴', callingCode: '+57' },
    { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', callingCode: '+506' },
    { code: 'CU', name: 'Cuba', flag: '🇨🇺', callingCode: '+53' },
    { code: 'DO', name: 'República Dominicana', flag: '🇩🇴', callingCode: '+1' },
    { code: 'EC', name: 'Ecuador', flag: '🇪🇨', callingCode: '+593' },
    { code: 'SV', name: 'El Salvador', flag: '🇸🇻', callingCode: '+503' },
    { code: 'GT', name: 'Guatemala', flag: '🇬🇹', callingCode: '+502' },
    { code: 'HN', name: 'Honduras', flag: '🇭🇳', callingCode: '+504' },
    { code: 'MX', name: 'México', flag: '🇲🇽', callingCode: '+52' },
    { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', callingCode: '+505' },
    { code: 'PA', name: 'Panamá', flag: '🇵🇦', callingCode: '+507' },
    { code: 'PY', name: 'Paraguay', flag: '🇵🇾', callingCode: '+595' },
    { code: 'PE', name: 'Perú', flag: '🇵🇪', callingCode: '+51' },
    { code: 'ES', name: 'España', flag: '🇪🇸', callingCode: '+34' },
    { code: 'UY', name: 'Uruguay', flag: '🇺🇾', callingCode: '+598' },
    { code: 'VE', name: 'Venezuela', flag: '🇻🇪', callingCode: '+58' },
    { code: 'US', name: 'Estados Unidos', flag: '🇺🇸', callingCode: '+1' },
    { code: 'CA', name: 'Canadá', flag: '🇨🇦', callingCode: '+1' },
    { code: 'BR', name: 'Brasil', flag: '🇧🇷', callingCode: '+55' },
    { code: 'FR', name: 'Francia', flag: '🇫🇷', callingCode: '+33' },
    { code: 'DE', name: 'Alemania', flag: '🇩🇪', callingCode: '+49' },
    { code: 'IT', name: 'Italia', flag: '🇮🇹', callingCode: '+39' },
    { code: 'JP', name: 'Japón', flag: '🇯🇵', callingCode: '+81' },
    { code: 'CN', name: 'China', flag: '🇨🇳', callingCode: '+86' },
    { code: 'IN', name: 'India', flag: '🇮🇳', callingCode: '+91' },
    { code: 'ZA', name: 'Sudáfrica', flag: '🇿🇦', callingCode: '+27' },
    { code: 'GB', name: 'Reino Unido', flag: '🇬🇧', callingCode: '+44' },
    { code: 'RU', name: 'Rusia', flag: '🇷🇺', callingCode: '+7' },
    { code: 'KR', name: 'Corea del Sur', flag: '🇰🇷', callingCode: '+82' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺', callingCode: '+61' },
    { code: 'NZ', name: 'Nueva Zelanda', flag: '🇳🇿', callingCode: '+64' },
];
